#!/bin/bash -e

version=$(cat package.json | jq -r '.version')
name=$(cat package.json | jq  -r '.electronProduct.name')
build=$(cat package.json | jq -r '.electronProduct.build')
dist=$(cat package.json | jq -r '.electronProduct.dist')

./node_modules/.bin/electron-packager \
  $(pwd) \
  $name \
  --platform darwin \
  --app-version $version \
  --build-version build.$build \
  --icon=$(pwd)/assets/AppIcon.icns \
  --out $dist \
  --overwrite
